# Generated by Django 5.2.7 on 2025-10-13 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('supplier_brand', models.CharField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Cost',
                'verbose_name_plural': 'Project Costs',
                'db_table': 'project_costs',
            },
        ),
        migrations.CreateModel(
            name='ProjectOverheads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('basis', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Overhead',
                'verbose_name_plural': 'Project Overheads',
                'db_table': 'project_overheads',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectOverheadVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overhead_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('basis', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('version_number', models.IntegerField()),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('project_overhead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='budget.projectoverheads')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.projects')),
            ],
            options={
                'db_table': 'project_overhead_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='projectoverheads',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overheads', to='budget.projects'),
        ),
        migrations.CreateModel(
            name='ProjectCostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_code', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('supplier_brand', models.CharField(blank=True, max_length=150, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('version_number', models.IntegerField()),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('project_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='budget.projectcosts')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.projects')),
            ],
            options={
                'db_table': 'project_cost_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='projectcosts',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='budget.projects'),
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('version_number', models.IntegerField()),
                ('change_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='budget.projects')),
            ],
            options={
                'db_table': 'project_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
