# Generated by Django 5.2.7 on 2025-10-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='e.g. Corporate Building Project', max_length=150)),
                ('category_code', models.CharField(help_text='e.g. A, B, C, D', max_length=10)),
                ('category_name', models.CharField(help_text='e.g. Civil & Structural Works', max_length=100)),
                ('item_description', models.CharField(help_text='e.g. Site preparation & excavation', max_length=255)),
                ('supplier_brand', models.CharField(blank=True, help_text='e.g. BuildSmart Contractors', max_length=150, null=True)),
                ('unit', models.CharField(help_text='e.g. Lump sum, m³, m², Nos', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='e.g. 200000', max_digits=15)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='e.g. 200.00', max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='e.g. 40000000.00', max_digits=15)),
                ('category_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total of the category', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Cost',
                'verbose_name_plural': 'Project Costs',
                'db_table': 'project_costs',
                'ordering': ['-created_at'],
            },
        ),
    ]
