# Generated by Django 5.2.7 on 2025-10-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOverheads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='e.g. Corporate Building Project', max_length=150)),
                ('overhead_type', models.CharField(help_text='e.g. Contingency, Contractor Margin', max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g. Provided in your BOQ', max_length=255, null=True)),
                ('basis', models.CharField(help_text='e.g. Percentage of BOQ', max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='e.g. 6.95, 10', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='e.g. 5350000, 8235000', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Overhead',
                'verbose_name_plural': 'Project Overheads',
                'db_table': 'project_overheads',
                'ordering': ['-created_at'],
            },
        ),
    ]
