# Generated by Django 5.2.7 on 2025-10-13 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_projectoverheads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Corporate Building Project', max_length=150)),
                ('location', models.CharField(blank=True, help_text='e.g. New York, NY', max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='projectcosts',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='projectoverheads',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='projectcosts',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. Lump sum, m³, m², Nos', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectoverheads',
            name='basis',
            field=models.CharField(blank=True, help_text='e.g. Percentage of BOQ', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectcosts',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Reference to the project', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.projects'),
        ),
        migrations.AddField(
            model_name='projectoverheads',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Reference to the project', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.projects'),
        ),
    ]
