# Generated by Django 5.2.7 on 2025-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_make_project_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcosts',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcostversion',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectoverheads',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectoverheadversion',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
