# Generated by Django 5.2.7 on 2025-10-13 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_projects_remove_projectcosts_project_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcosts',
            name='version_number',
            field=models.PositiveIntegerField(default=1, help_text='Current version number'),
        ),
        migrations.AddField(
            model_name='projectoverheads',
            name='version_number',
            field=models.PositiveIntegerField(default=1, help_text='Current version number'),
        ),
        migrations.CreateModel(
            name='ProjectCostVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(help_text='e.g. A, B, C, D', max_length=10)),
                ('category_name', models.CharField(help_text='e.g. Civil & Structural Works', max_length=100)),
                ('item_description', models.CharField(help_text='e.g. Site preparation & excavation', max_length=255)),
                ('supplier_brand', models.CharField(blank=True, help_text='e.g. BuildSmart Contractors', max_length=150, null=True)),
                ('unit', models.CharField(blank=True, help_text='e.g. Lump sum, m³, m², Nos', max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='e.g. 200000', max_digits=15)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, help_text='e.g. 200.00', max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='e.g. 40000000.00', max_digits=15)),
                ('category_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total of the category', max_digits=15, null=True)),
                ('version_number', models.PositiveIntegerField(help_text='Version number at the time of this record')),
                ('change_reason', models.CharField(default='Updated', help_text='Reason for the change', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_record', models.ForeignKey(help_text='Reference to the original record', on_delete=django.db.models.deletion.CASCADE, to='budget.projectcosts')),
                ('project', models.ForeignKey(blank=True, help_text='Reference to the project', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.projects')),
            ],
            options={
                'verbose_name': 'Project Cost Version',
                'verbose_name_plural': 'Project Cost Versions',
                'db_table': 'project_cost_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOverheadVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_type', models.CharField(help_text='e.g. Contingency, Contractor Margin', max_length=50)),
                ('description', models.CharField(blank=True, help_text='e.g. Provided in your BOQ', max_length=255, null=True)),
                ('basis', models.CharField(blank=True, help_text='e.g. Percentage of BOQ', max_length=100, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='e.g. 6.95, 10', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, help_text='e.g. 5350000, 8235000', max_digits=15)),
                ('version_number', models.PositiveIntegerField(help_text='Version number at the time of this record')),
                ('change_reason', models.CharField(default='Updated', help_text='Reason for the change', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this version was created')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_record', models.ForeignKey(help_text='Reference to the original record', on_delete=django.db.models.deletion.CASCADE, to='budget.projectoverheads')),
                ('project', models.ForeignKey(blank=True, help_text='Reference to the project', null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.projects')),
            ],
            options={
                'verbose_name': 'Project Overhead Version',
                'verbose_name_plural': 'Project Overhead Versions',
                'db_table': 'project_overhead_versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
