# Generated by Django 5.2.8 on 2025-11-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_add_is_delete_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
