# Generated by Django 5.2.8 on 2025-11-27 07:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_populate_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
