# Generated by Django 5.2.7 on 2025-10-09 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAPIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('total_results', models.IntegerField()),
                ('next_page', models.CharField(blank=True, max_length=100, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('query_params', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('article_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField()),
                ('pub_date_tz', models.CharField(default='UTC', max_length=10)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_id', models.CharField(max_length=100)),
                ('source_name', models.CharField(max_length=200)),
                ('source_priority', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_icon', models.URLField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(max_length=50)),
                ('country', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('creator', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['pub_date'], name='news_newsar_pub_dat_8ff222_idx'), models.Index(fields=['source_id'], name='news_newsar_source__5f0f01_idx'), models.Index(fields=['language'], name='news_newsar_languag_e5c680_idx')],
            },
        ),
    ]
