# Generated by Django 5.2.7 on 2025-10-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision_key', models.CharField(max_length=50)),
                ('decision', models.TextField()),
                ('reason', models.TextField()),
                ('suggestion', models.TextField()),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.CharField(blank=True, max_length=500, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('old_supplier_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('old_rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('old_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_supplier_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('new_rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cost_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('impact_reason', models.TextField(blank=True, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='news_alert_created_288408_idx'), models.Index(fields=['is_accept'], name='news_alert_is_acce_2e2d15_idx'), models.Index(fields=['decision_key'], name='news_alert_decisio_d8848a_idx')],
            },
        ),
    ]
