# Generated by Django 5.2.7 on 2025-10-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_accept',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_sent'], name='news_alert_is_sent_af8221_idx'),
        ),
    ]
