# Generated by Django 5.2.7 on 2025-11-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alert_is_sent_alter_alert_is_accept_and_more'),
    ]

    operations = [
    ]
