# Generated by Django 5.2.7 on 2025-11-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_project_id_column'),
    ]

    operations = [
    ]
