# Generated by Django 5.2.7 on 2025-11-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_add_is_delete_field'),
        ('news', '0005_add_project_id_field_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='project_id',
            field=models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.projects'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['project_id'], name='news_alert_project_ab2180_idx'),
        ),
    ]
