# Generated by Django 5.2.7 on 2025-10-14 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedCost',
            fields=[
                ('updated_cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_location', models.CharField(blank=True, max_length=500, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost_line_items', models.JSONField(default=list)),
                ('overheads', models.JSONField(default=list)),
                ('is_accept', models.BooleanField(blank=True, default=False, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_costing_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_costs', to='chatapp.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_costs', to='chatapp.messages')),
            ],
            options={
                'verbose_name': 'Updated Cost',
                'verbose_name_plural': 'Updated Costs',
                'db_table': 'updated_costs',
                'ordering': ['-created_at'],
            },
        ),
    ]
