# Generated by Django 5.2.7 on 2025-10-16 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('chatapp', '0003_messages_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='budget.projects'),
        ),
    ]
