# Generated by Django 5.2.7 on 2025-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_conversation_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_hide',
            field=models.BooleanField(default=False),
        ),
    ]
