# Generated by Django 5.2.7 on 2025-10-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_messages_is_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_accept',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
