# Generated by Django 5.2.7 on 2025-10-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
